name: marinamoda
description: 'The music industry has undergone significant transformations in recent years, thanks to the advent of technology and the digital age. Streaming services have become the primary mode of music consumption, with giants like Spotify, Apple Music, and Amazon Music dominating the market. While these platforms offer convenience and access to a vast library of music, they come with their fair share of challenges, including centralized control, unfair artist compensation, and data privacy concerns. In response to these issues, a groundbreaking solution has emerged: Marina.Moda, a decentralized music streaming service powered by artificial intelligence (AI).'
publish_to: 'none'
version: 1.0.3+8

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Introducation screen
  introduction_screen: ^3.0.2

  url_launcher: ^6.0.17

  #check internet connection
  connectivity: ^3.0.6

  #Bottom menu
  salomon_bottom_bar: ^3.3.1

  #Shared Preference
  shared_preferences: ^2.0.15
  
  #Google Fonts
  google_fonts: ^4.0.3
  sliding_switch: ^1.0.0
  provider: ^6.0.3
  flutter_arc_speed_dial: ^2.0.0
  flutter_svg: ^1.0.3
  flex_color_picker: ^3.3.0
  dots_indicator: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_inappwebview: ^5.8.0
  flutter_app_name: ^0.1.1
  flutter_native_splash: 
  google_mobile_ads: ^4.0.0
  location: ^5.0.3

  permission_handler: ^10.1.0
  flutter_downloader: ^1.8.4
  path_provider: ^2.0.11

  #OneSignal Notification
  onesignal_flutter: ^5.2.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  
flutter_app_name:
  name: "Universal Web"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/splash logo.png"

flutter_native_splash:
  background_image: assets/icon/splash.png
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
